### ISSUE TITLE
storage_class default set to null to take default from cluster

### ISSUE THREAD

**Issue by nachtfisch** [nickytd/kubernetes-logging-helm#4] opened 2021-10-08 13:28 UTC
Storage class default in 

https://github.com/nickytd/kubernetes-logging-helm/blob/d85d670f148128fb7e5372e1c4be8643af9406ec/charts/values.yaml#L6

is set to `default`

If set to `null` the cluster default will be taken.

`
storage_class: null
`

Not as critical since  value can be already easily overwritten to `null`.

Added fix in PR.

**Comment by nickytd** [comment] 2021-11-14 19:26
Thanks, the issue is fixed in 2.4.1 release

**Closed by nickytd** 2021-11-14 19:26 UTC
